server:
 port: 8090

keystore:
 password: mySecretKey
spring:
  application:
    name: auth-service
  mvc:
    dispatchOptionsRequest: true
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    

