spring:
  application:
    name: portal
  datasource:
   tomcat:
     initial-size: 2   
security:
 oauth2:
   resource:
     accessTokenUri: http://${DOCKER_HOST_IP}:8090/oauth/check_token
     userAuthorizationUri: http://${DOCKER_HOST_IP}:8090/oauth/authorize
     userInfoUri: http://${DOCKER_HOST_IP}:8090/user
     jwt:
       keyUri: http://${DOCKER_HOST_IP}:8090/oauth/token_key
server:
 port: 8003
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${DOCKER_HOST_IP}:8761/eureka/
#  instance:
#    instanceId: ${spring.application.name}
#    hostname: ${DOCKER_HOST_IP}:${server.port}
